export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_HEADPHONES_REQUEST = "GET_HEADPHONES_REQUEST";
export const GET_HEADPHONES_SUCCESS = "GET_HEADPHONES_SUCCESS";
export const GET_HEADPHONES_FAIL = "GET_HEADPHONES_FAIL";

export const GET_EARPHONES_REQUEST = "GET_EARPHONES_REQUEST";
export const GET_EARPHONES_SUCCESS = "GET_EARPHONES_SUCCESS";
export const GET_EARPHONES_FAIL = "GET_EARPHONES_FAIL";

export const GET_SPEAKERS_REQUEST = "GET_SPEAKERS_REQUEST";
export const GET_SPEAKERS_SUCCESS = "GET_SPEAKERS_SUCCESS";
export const GET_SPEAKERS_FAIL = "GET_SPEAKERS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";
